modLoader="javafml" #mandatory
loaderVersion="[32,)" #mandatory (24 is current forge version)
issueTrackerURL="http://github.com/ben_mkiv/MobTools/issues" #optional
displayURL="https://minecraft.curseforge.com/projects/???" #optional
#logoFile="mobtools.png" #optional
credits="ben_mkiv (code), luni (for the inspiration to create this mod)" #optional
authors="ben_mkiv" #optional
[[mods]] #mandatory
modId="mobtools" #mandatory
version="${file.jarVersion}" #mandatory
displayName="MobTools" #mandatory
#updateJSONURL="" #optional
# The description text for the mod (multi line!) (#mandatory)
description='''
its a mod'''